services:

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./proyecto:/var/www/html

  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
    volumes:
    - ./initdb/proyectoDump.sql:/docker-entrypoint-initdb.d/proyectoDump.sql # Volumenes para cargar las db
    - ./initdb/proyectoDumpTest.sql:/docker-entrypoint-initdb.d/proyectoDumpTest.sql

    #- ./mysql:/var/lib/mysql # Volumen para mantener todos los datos

  mailer:
    image: axllent/mailpit
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1